// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKt7TLMTHnqYXo1mbegDqfsuINbSw4_IE',
    appId: '1:1028594382680:android:5cf458d204166ae8f1172d',
    messagingSenderId: '1028594382680',
    projectId: 'wastetowealth-195e3',
    databaseURL: 'https://wastetowealth-195e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wastetowealth-195e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBherliQESUpHpjsxqBVfNarYkdOPkD2Mg',
    appId: '1:1028594382680:ios:f276c26a09b77821f1172d',
    messagingSenderId: '1028594382680',
    projectId: 'wastetowealth-195e3',
    databaseURL: 'https://wastetowealth-195e3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wastetowealth-195e3.firebasestorage.app',
    iosBundleId: 'com.example.projectSel',
  );
}
